create database golf_booking;
use golf_booking;

CREATE TABLE users (
    id VARCHAR(36) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    username VARCHAR(255) UNIQUE NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    phone VARCHAR(20),
    profile_picture VARCHAR(255),
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE tee_times (
    id VARCHAR(36) PRIMARY KEY,
    course VARCHAR(255) NOT NULL,
    date DATE NOT NULL,
    time TIME NOT NULL,
    holes VARCHAR(10) NOT NULL,
    available BOOLEAN DEFAULT true,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE bookings (
    id VARCHAR(36) PRIMARY KEY,
    UserId VARCHAR(36) NOT NULL,
    TeeTimeId VARCHAR(36) NOT NULL,
    players INT NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (UserId) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (TeeTimeId) REFERENCES tee_times(id) ON DELETE CASCADE,
    CONSTRAINT check_players CHECK (players >= 1 AND players <= 4)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
